import React, { useEffect, useRef, useState } from "react";
import Canvas from "@components/canvas/Canvas";
import { BoardProps } from "@types";
import styles from "./Board.module.scss";

function Board({ socket, user, setUser, elements, setElements }: BoardProps) {
	const canvasRef = useRef<HTMLCanvasElement | null>(null);
	const ctx = useRef<CanvasRenderingContext2D | null>(null);

	const [color, setRandomColor] = useState<string>("#000000");

	/**
	 * @description When the component mounts, set the random color
	 */
	useEffect(() => {
		const randomColor = generateRandomColor();
		setRandomColor(randomColor);
	}, []);

	const handleLogout = () => {
		const { userId } = JSON.parse(sessionStorage.getItem("user"));

		sessionStorage.clear();
		setUser(null);
		socket.emit("logout", userId);
	};

	return (
		<>
			<input
				className={styles.LogoutButton}
				type={"button"}
				value={"Logout"}
				onClick={() => handleLogout()}
			/>
			<Canvas
				socket={socket}
				canvasRef={canvasRef}
				ctx={ctx}
				color={color}
				setElements={setElements}
				elements={elements}
				user={user}
			/>
		</>
	);
}

export default Board;

/**
 * @name generateRandomColor
 * @description Generate a random color
 * The color is generated by generating a random number between 0 and 16777215
 * The number is then converted to a hex string
 * The hex string is padded with 0s to ensure it is 6 characters long
 */
function generateRandomColor() {
	const maxVal = 0xffffff; // 16777215
	let randomNumber = Math.random() * maxVal;
	randomNumber = Math.floor(randomNumber);
	const randomString = randomNumber.toString(16);
	const randColor = randomString.padStart(6, "0");
	return `#${randColor.toUpperCase()}`;
}
